name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install test dependencies
      run: |
        wget https://github.com/Snaipe/Criterion/releases/download/v2.3.3/criterion-v2.3.3-linux-x86_64.tar.bz2
        tar xjf criterion-v2.3.3-linux-x86_64.tar.bz2
        sudo sh -c "echo "/usr/local/lib" > /etc/ld.so.conf.d/criterion.conf"
        sudo cp -r include/* /usr/local/include
        sudo cp -r lib/* /usr/local/lib
        sudo cp -r share/* /usr/local/share
        sudo ldconfig
        python3 -m pip install gcovr
    - name: make
      run: make
    - name: make tests_run
      run: make tests_run
